#!/bin/bash
curl -XDELETE http://localhost:9220/diidw
echo "Delete diidw"
curl -XDELETE http://localhost:9220/biosis
echo "Delete biosis"
curl -XDELETE http://localhost:9220/rsci
echo "Delete rsci"
curl -XDELETE http://localhost:9220/arci
echo "Delete arci"
curl -XDELETE http://localhost:9220/bci
echo "Delete bci"
curl -XDELETE http://localhost:9220/medline
echo "Delete medline"
curl -XDELETE http://localhost:9220/cscd
echo "Delete cscd"
curl -XDELETE http://localhost:9220/kjd
echo "Delete kjd"
curl -XDELETE http://localhost:9220/drci
echo "Delete drci"
curl -XDELETE http://localhost:9220/inspec
echo "Delete inspec"
curl -XDELETE http://localhost:9220/wos
echo "Delete wos"
curl -XDELETE http://localhost:9220/bioabs
echo "Delete bioabs"
curl -XDELETE http://localhost:9220/ccc
echo "Delete ccc"
curl -XDELETE http://localhost:9220/superunif
echo "Delete superunif"
curl -XDELETE http://localhost:9220/zoorec
echo "Delete zoorec"
curl -XDELETE http://localhost:9220/fsta
echo "Delete fsta"
curl -XDELETE http://localhost:9220/cabi
echo "Delete cabi"
curl -XDELETE http://localhost:9220/scielo
echo "Delete scielo"
curl -XDELETE http://localhost:9220/gci
echo "Delete gci"
